### ISSUE TITLE
Add Akashic Tome

### ISSUE THREAD

**Issue by DolphinJR** [Eventyria/Satisfactoria-mod-pack#8]
It would be very usefull to have a book that stores all mods guide books!
![image](https://user-images.githubusercontent.com/88281961/215076935-fac6b522-ea07-4b41-91a2-64191bb69550.png)

**Comment by DolphinJR** [comment]
For some reason i can't add label (mod suggestion"

**Comment by Eventyria** [comment]
Has been added for the new build!
